Bugfix: decimal separator parsing
PoE-Overlay-Community/PoE-Overlay-Community-Fork pull request #180
Opened 2021-02-03 17:38 UTC by WhiteFang5

## Description

* Fixed parsing of 'stackSize' values that contain a decimal separator
* Changed some of the item properties from textual values to actual numbers
* Updated item templates/displays accordingly to support this change.

## Replication Steps

price-check any of the following items:
```Rarity: Currency
Orb of Alteration
--------
Stack Size: 1,059/20
--------
Reforges a magic item with new random modifiers
--------
Right click this item then left click a magic item to apply it.
Shift click to unstack.
```
```
Rarity: Currency
Orb of Alteration
--------
Stack Size: 1.059/20
--------
Reforges a magic item with new random modifiers
--------
Right click this item then left click a magic item to apply it.
Shift click to unstack.
```
```
Rarity: Currency
Orb of Alteration
--------
Stack Size: 1059/20
--------
Reforges a magic item with new random modifiers
--------
Right click this item then left click a magic item to apply it.
Shift click to unstack.
```
Only some of them work, while others result in a stack size of `1`.  
The expected result would be that they're all considered equal, which is that this PR is fixing.

## How Has This Been Tested?

- [ ] ran `npm run ng:lint`
- [ ] ran `npm run format`
- [ ] ran `npm run ng:test`
- [ ] added unit tests
- [x] manually tested

2021-02-12 15:24 UTC, wratho requested changes

2021-02-12 15:25 UTC, WhiteFang5 commented on src/app/shared/module/poe/service/item/query/item-search-filters-miscs.service.ts
> +      const exp = +(splittedExp[0] || '').split("., ").join('')
Fixed the regex thing in https://github.com/PoE-Overlay-Community/PoE-Overlay-Community-Fork/pull/180/commits/96e7fb6e1222ecc53c9fb8191ce49022dfc14cd2

2021-02-12 15:50 UTC, WhiteFang5 commented on src/app/shared/module/poe/service/item/parser/item-section-properties-parser.service.ts
> +      return [undefined, false];
The return value is later on split into its variables again (`const [text, augmented] = this.parsePhrase(line, phrase);`), and then `text` if checked if "it's not defined" using `if (!text) return;`. I'm no TypeScript expert, but I believe that if `''` is returned, it the if-statement would evaluate to be false (and this skip the early return)

2021-02-18 17:39 UTC, WhiteFang5 commented on src/app/shared/module/poe/service/item/parser/item-section-properties-parser.service.ts
> +      return [undefined, false];
Changed to empty string in b2f8b884d7102ca4d8db4b2f44d65e40f5b43db4

2021-02-18 17:45 UTC, WhiteFang5 commented on src/app/shared/module/poe/service/item/query/item-search-filters-miscs.service.ts
> +      const exp = +(splittedExp[0] || '').split("., ").join('')
Fixed in e08624b6930f4c280b3ab6cb3dc471e1819ad54e

2021-02-18 17:51 UTC, wratho approved these changes

2021-02-18 17:54 UTC, merged